# Generated by Django 3.1 on 2020-08-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.IntegerField(default=91),
            preserve_default=False,
        ),
    ]
