# Generated by Django 3.1 on 2020-08-24 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAccount', '0003_auto_20200824_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91 9876543210'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
